### ISSUE TITLE
Accountancy find method fail for subclassed entries

### ISSUE THREAD

**Issue by AndreasZaschka** [st-tu-dresden/salespoint#118]
After updating the test (90c24e138b2a2db0c50b518e0f2d8ecdbe0376aa) i recognized an mistake searching for subclassed `AccountancyEntry`s.
Due to the the [JavaDoc](http://st.inf.tu-dresden.de/SalesPoint/api/org/salespointframework/accountancy/Accountancy.html#find-java.time.LocalDateTime-java.time.LocalDateTime-) the find method should only return the entries of the subclass.

StackTrace:

``` [java]
Expected: an iterable with size <4>
     but: iterable size was <7>
java.lang.AssertionError
Expected: an iterable with size <4>
     but: iterable size was <7>
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at org.junit.Assert.assertThat(Assert.java:956)
    at org.junit.Assert.assertThat(Assert.java:923)
    at org.salespointframework.accountancy.AccountancyTests.selectType(AccountancyTests.java:94)
```

**Comment by odrotbohm** [comment]
Fixed with #314.
